//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoG.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the left or right arrow to see the next event.
        /// </summary>
        public static string ACTIVITY_ClickOnTheLeftOrRigthArrow {
            get {
                return ResourceManager.GetString("ACTIVITY_ClickOnTheLeftOrRigthArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented file.
        /// </summary>
        public static string ACTIVITY_CommentedFile {
            get {
                return ResourceManager.GetString("ACTIVITY_CommentedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created a new file.
        /// </summary>
        public static string ACTIVITY_CreatedFile {
            get {
                return ResourceManager.GetString("ACTIVITY_CreatedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created a new project.
        /// </summary>
        public static string ACTIVITY_CreatedProject {
            get {
                return ResourceManager.GetString("ACTIVITY_CreatedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is what happened in {0}.
        /// </summary>
        public static string ACTIViTY_HereIsWhatHappened {
            get {
                return ResourceManager.GetString("ACTIViTY_HereIsWhatHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string ACTIVITY_SeeAll {
            get {
                return ResourceManager.GetString("ACTIVITY_SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string COMMON_AreYouSure {
            get {
                return ResourceManager.GetString("COMMON_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string COMMON_BY {
            get {
                return ResourceManager.GetString("COMMON_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string COMMON_Cancel {
            get {
                return ResourceManager.GetString("COMMON_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string COMMON_CreatedOn {
            get {
                return ResourceManager.GetString("COMMON_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string COMMON_CreateNewProject {
            get {
                return ResourceManager.GetString("COMMON_CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string COMMON_Description {
            get {
                return ResourceManager.GetString("COMMON_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My cart.
        /// </summary>
        public static string COMMON_DownloadCart {
            get {
                return ResourceManager.GetString("COMMON_DownloadCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string COMMON_Files {
            get {
                return ResourceManager.GetString("COMMON_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string COMMON_Friends {
            get {
                return ResourceManager.GetString("COMMON_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invits.
        /// </summary>
        public static string COMMON_Invits {
            get {
                return ResourceManager.GetString("COMMON_Invits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string COMMON_Latest {
            get {
                return ResourceManager.GetString("COMMON_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo..
        /// </summary>
        public static string COMMON_LoremIpsum {
            get {
                return ResourceManager.GetString("COMMON_LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string COMMON_Messages {
            get {
                return ResourceManager.GetString("COMMON_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Projects.
        /// </summary>
        public static string COMMON_NewProjects {
            get {
                return ResourceManager.GetString("COMMON_NewProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess you don&apos;t have the right to do so.....
        /// </summary>
        public static string COMMON_PermissionDenied {
            get {
                return ResourceManager.GetString("COMMON_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string COMMON_Save {
            get {
                return ResourceManager.GetString("COMMON_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string COMMON_Submit {
            get {
                return ResourceManager.GetString("COMMON_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string COMMON_Tags {
            get {
                return ResourceManager.GetString("COMMON_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest notifications.
        /// </summary>
        public static string DASHBOARD_LatestNotifications {
            get {
                return ResourceManager.GetString("DASHBOARD_LatestNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DASHBOARD_PageTitle {
            get {
                return ResourceManager.GetString("DASHBOARD_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string FILE_Accept {
            get {
                return ResourceManager.GetString("FILE_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string FILE_Activity {
            get {
                return ResourceManager.GetString("FILE_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files....
        /// </summary>
        public static string FILE_AddFiles {
            get {
                return ResourceManager.GetString("FILE_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string FILE_AddToDownloadCart {
            get {
                return ResourceManager.GetString("FILE_AddToDownloadCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string FILE_Administration {
            get {
                return ResourceManager.GetString("FILE_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel upload.
        /// </summary>
        public static string FILE_CancelUpload {
            get {
                return ResourceManager.GetString("FILE_CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Please, bring your own cloud :) &lt;/strong&gt;&lt;br/&gt; Files are yours, you have to register an online storage account before uploading anything....
        /// </summary>
        public static string FILE_Create_NoCloudStorage {
            get {
                return ResourceManager.GetString("FILE_Create_NoCloudStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string FILE_Create_StorageLink {
            get {
                return ResourceManager.GetString("FILE_Create_StorageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FILE_Delete {
            get {
                return ResourceManager.GetString("FILE_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File details.
        /// </summary>
        public static string FILE_Detail {
            get {
                return ResourceManager.GetString("FILE_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string FILE_DetailTitle {
            get {
                return ResourceManager.GetString("FILE_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FILE_Download {
            get {
                return ResourceManager.GetString("FILE_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string FILE_Downloaded {
            get {
                return ResourceManager.GetString("FILE_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string FILE_Edit {
            get {
                return ResourceManager.GetString("FILE_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FILE_FileName {
            get {
                return ResourceManager.GetString("FILE_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FILE_Files {
            get {
                return ResourceManager.GetString("FILE_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string FILE_General {
            get {
                return ResourceManager.GetString("FILE_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked.
        /// </summary>
        public static string FILE_Likes {
            get {
                return ResourceManager.GetString("FILE_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        public static string FILE_Metrics {
            get {
                return ResourceManager.GetString("FILE_Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last update.
        /// </summary>
        public static string FILE_ModifiedOn {
            get {
                return ResourceManager.GetString("FILE_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played.
        /// </summary>
        public static string FILE_Played {
            get {
                return ResourceManager.GetString("FILE_Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posted on .
        /// </summary>
        public static string FILE_PostedOn {
            get {
                return ResourceManager.GetString("FILE_PostedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to step 2.
        /// </summary>
        public static string FILE_ProceedStep2 {
            get {
                return ResourceManager.GetString("FILE_ProceedStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string FILE_Processing {
            get {
                return ResourceManager.GetString("FILE_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        public static string FILE_Promote {
            get {
                return ResourceManager.GetString("FILE_Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string FILE_Reject {
            get {
                return ResourceManager.GetString("FILE_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string FILE_Reset {
            get {
                return ResourceManager.GetString("FILE_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string FILE_Start {
            get {
                return ResourceManager.GetString("FILE_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start upload.
        /// </summary>
        public static string FILE_StartUpload {
            get {
                return ResourceManager.GetString("FILE_StartUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FILE_Title {
            get {
                return ResourceManager.GetString("FILE_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel #1 : find something....
        /// </summary>
        public static string HOME_CAROUSEL_1 {
            get {
                return ResourceManager.GetString("HOME_CAROUSEL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel #2 : another something....
        /// </summary>
        public static string HOME_CAROUSEL_2 {
            get {
                return ResourceManager.GetString("HOME_CAROUSEL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel #3 : and another something....
        /// </summary>
        public static string HOME_CAROUSEL_3 {
            get {
                return ResourceManager.GetString("HOME_CAROUSEL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string HOME_Email {
            get {
                return ResourceManager.GetString("HOME_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  thanks :) &lt;br /&gt; we&apos;ll keep in touch soon..
        /// </summary>
        public static string HOME_FeedbackThx {
            get {
                return ResourceManager.GetString("HOME_FeedbackThx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are interested, drop us your email..
        /// </summary>
        public static string HOME_IfYouAreInterested {
            get {
                return ResourceManager.GetString("HOME_IfYouAreInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Me!.
        /// </summary>
        public static string HOME_InvitMe {
            get {
                return ResourceManager.GetString("HOME_InvitMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New members.
        /// </summary>
        public static string HOME_NewMembers {
            get {
                return ResourceManager.GetString("HOME_NewMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Work.
        /// </summary>
        public static string HOME_RecentWork {
            get {
                return ResourceManager.GetString("HOME_RecentWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... thanks for joining in.
        /// </summary>
        public static string HOME_ThanksJoining {
            get {
                return ResourceManager.GetString("HOME_ThanksJoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... this is happening right now.
        /// </summary>
        public static string HOME_ThisIsHappening {
            get {
                return ResourceManager.GetString("HOME_ThisIsHappening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all members.
        /// </summary>
        public static string HOME_ViewAllMembers {
            get {
                return ResourceManager.GetString("HOME_ViewAllMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all recents.
        /// </summary>
        public static string HOME_ViewAllRecent {
            get {
                return ResourceManager.GetString("HOME_ViewAllRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Welcome to Flabbit. &lt;br /&gt; Yet another online music collaboration site..
        /// </summary>
        public static string HOME_WelcomeHeader {
            get {
                return ResourceManager.GetString("HOME_WelcomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re in a private beta.
        /// </summary>
        public static string HOME_WelcomeLead {
            get {
                return ResourceManager.GetString("HOME_WelcomeLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invit someone.
        /// </summary>
        public static string INViT_InvitSomeone {
            get {
                return ResourceManager.GetString("INViT_InvitSomeone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string MAIL_Archive {
            get {
                return ResourceManager.GetString("MAIL_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string MAIL_BtnSend {
            get {
                return ResourceManager.GetString("MAIL_BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string MAIL_For {
            get {
                return ResourceManager.GetString("MAIL_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string MAIL_Inbox {
            get {
                return ResourceManager.GetString("MAIL_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MAIL_Message {
            get {
                return ResourceManager.GetString("MAIL_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string MAIL_NewMessage {
            get {
                return ResourceManager.GetString("MAIL_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argh! you broke it..
        /// </summary>
        public static string MAIL_SendError {
            get {
                return ResourceManager.GetString("MAIL_SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string MAIL_Sent {
            get {
                return ResourceManager.GetString("MAIL_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string MAIL_Subject {
            get {
                return ResourceManager.GetString("MAIL_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My.
        /// </summary>
        public static string MAINMENU_My {
            get {
                return ResourceManager.GetString("MAINMENU_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My messages.
        /// </summary>
        public static string MAINMENU_MyMessages {
            get {
                return ResourceManager.GetString("MAINMENU_MyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MAINMENU_MyProfil {
            get {
                return ResourceManager.GetString("MAINMENU_MyProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My projects.
        /// </summary>
        public static string MAINMENU_MyProjects {
            get {
                return ResourceManager.GetString("MAINMENU_MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string MAINMENU_Popular {
            get {
                return ResourceManager.GetString("MAINMENU_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MAINMENU_Profile {
            get {
                return ResourceManager.GetString("MAINMENU_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MAINMENU_Project {
            get {
                return ResourceManager.GetString("MAINMENU_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My projects.
        /// </summary>
        public static string MAINMENU_Projects {
            get {
                return ResourceManager.GetString("MAINMENU_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string MAINMENU_Random {
            get {
                return ResourceManager.GetString("MAINMENU_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string NOTIFICATION_Never {
            get {
                return ResourceManager.GetString("NOTIFICATION_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a day.
        /// </summary>
        public static string NOTIFICATION_OnceADay {
            get {
                return ResourceManager.GetString("NOTIFICATION_OnceADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once an hour.
        /// </summary>
        public static string NOTIFICATION_OnceAnHour {
            get {
                return ResourceManager.GetString("NOTIFICATION_OnceAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity feed.
        /// </summary>
        public static string PROFILE_ActivityFeed {
            get {
                return ResourceManager.GetString("PROFILE_ActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string PROFILE_Alerts {
            get {
                return ResourceManager.GetString("PROFILE_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string PROFILE_Avatar {
            get {
                return ResourceManager.GetString("PROFILE_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your avatar.
        /// </summary>
        public static string PROFILE_ChangeAvatar {
            get {
                return ResourceManager.GetString("PROFILE_ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string PROFILE_Dashboard {
            get {
                return ResourceManager.GetString("PROFILE_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects I follow.
        /// </summary>
        public static string PROFILE_FOLLOWED {
            get {
                return ResourceManager.GetString("PROFILE_FOLLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined on.
        /// </summary>
        public static string PROFILE_JoinedOn {
            get {
                return ResourceManager.GetString("PROFILE_JoinedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string PROFILE_Language {
            get {
                return ResourceManager.GetString("PROFILE_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My settings.
        /// </summary>
        public static string PROFILE_MySettings {
            get {
                return ResourceManager.GetString("PROFILE_MySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any file in your cart!.
        /// </summary>
        public static string PROFILE_NoFileInCart {
            get {
                return ResourceManager.GetString("PROFILE_NoFileInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string PROFILE_Notifications {
            get {
                return ResourceManager.GetString("PROFILE_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PROFILE_PageTitle {
            get {
                return ResourceManager.GetString("PROFILE_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See detail....
        /// </summary>
        public static string PROFILE_SeeDetail {
            get {
                return ResourceManager.GetString("PROFILE_SeeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string PROFILE_Storage {
            get {
                return ResourceManager.GetString("PROFILE_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fridge.
        /// </summary>
        public static string PROFILE_TheFridge {
            get {
                return ResourceManager.GetString("PROFILE_TheFridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string PROJECT_Activity {
            get {
                return ResourceManager.GetString("PROJECT_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork.
        /// </summary>
        public static string PROJECT_Admin_Artwork {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Artwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collabs.
        /// </summary>
        public static string PROJECT_Admin_Collabs {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Collabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string PROJECT_Admin_Comments {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string PROJECT_Admin_Follow {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invits.
        /// </summary>
        public static string PROJECT_Admin_Invits {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Invits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string PROJECT_Admin_Notes {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string PROJECT_Admin_Parameters {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string PROJECT_Admin_Reports {
            get {
                return ResourceManager.GetString("PROJECT_Admin_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string PROJECT_Administration {
            get {
                return ResourceManager.GetString("PROJECT_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string PROJECT_AdminOn {
            get {
                return ResourceManager.GetString("PROJECT_AdminOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string PROJECT_By {
            get {
                return ResourceManager.GetString("PROJECT_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to listen.
        /// </summary>
        public static string PROJECT_ClickToPlay {
            get {
                return ResourceManager.GetString("PROJECT_ClickToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string PROJECT_Create_Licence {
            get {
                return ResourceManager.GetString("PROJECT_Create_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;i class=&quot;icon-phone&quot;&gt;&lt;/i&gt; &lt;abbr title=&quot;CC-BY&quot;&gt;BY&lt;/abbr&gt; Attribution — This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.&lt;/p&gt;
        ///            &lt;p&gt;&lt;i class=&quot;icon-envelope-alt&quot;&gt;&lt;/i&gt; &lt;abbr title=&quot;CC-NC&quot;&gt;NC&lt;/abbr&gt; NonCommercial - This license lets others remix, tweak, and build upon your work non [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PROJECT_Create_LicenceDescription {
            get {
                return ResourceManager.GetString("PROJECT_Create_LicenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is an explanation of the licences.....
        /// </summary>
        public static string PROJECT_Create_LicenceExplain {
            get {
                return ResourceManager.GetString("PROJECT_Create_LicenceExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation....
        /// </summary>
        public static string PROJECT_Create_Title {
            get {
                return ResourceManager.GetString("PROJECT_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description.
        /// </summary>
        public static string PROJECT_Description {
            get {
                return ResourceManager.GetString("PROJECT_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string PROJECT_Detail {
            get {
                return ResourceManager.GetString("PROJECT_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string PROJECT_Files {
            get {
                return ResourceManager.GetString("PROJECT_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string PROJECT_Files_Owner {
            get {
                return ResourceManager.GetString("PROJECT_Files_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed by.
        /// </summary>
        public static string PROJECT_Follows {
            get {
                return ResourceManager.GetString("PROJECT_Follows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string PROJECT_General {
            get {
                return ResourceManager.GetString("PROJECT_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modification.
        /// </summary>
        public static string PROJECT_LastModification {
            get {
                return ResourceManager.GetString("PROJECT_LastModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string PROJECT_Licence {
            get {
                return ResourceManager.GetString("PROJECT_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project was liked.
        /// </summary>
        public static string PROJECT_liked {
            get {
                return ResourceManager.GetString("PROJECT_liked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string PROJECT_NewProject {
            get {
                return ResourceManager.GetString("PROJECT_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no file to show....
        /// </summary>
        public static string PROJECT_NoFiles {
            get {
                return ResourceManager.GetString("PROJECT_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string PROJECT_Popular {
            get {
                return ResourceManager.GetString("PROJECT_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string PROJECT_Random {
            get {
                return ResourceManager.GetString("PROJECT_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string PROJECT_Tags {
            get {
                return ResourceManager.GetString("PROJECT_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time(s).
        /// </summary>
        public static string PROJECT_Times {
            get {
                return ResourceManager.GetString("PROJECT_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string PROJECT_UploadFile {
            get {
                return ResourceManager.GetString("PROJECT_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send invit.
        /// </summary>
        public static string SOCIAL_btnInvit {
            get {
                return ResourceManager.GetString("SOCIAL_btnInvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invits.
        /// </summary>
        public static string SOCIAL_Invits {
            get {
                return ResourceManager.GetString("SOCIAL_Invits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox registration failed.
        /// </summary>
        public static string STORAGE_RegisterDropboxFailed {
            get {
                return ResourceManager.GetString("STORAGE_RegisterDropboxFailed", resourceCulture);
            }
        }
    }
}
